/* Generated by `npm run api:types` from the backend's OpenAPI document. Do not edit. */
export interface paths {
    "/api/events/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["detail"];
        put: operations["update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/venues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tickets/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["scan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["mine"];
        put?: never;
        post: operations["pay"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["close"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list"];
        put?: never;
        post: operations["create_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["publish"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["cancel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{eventId}/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["status"];
        put?: never;
        post: operations["join"];
        delete: operations["leave"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{eventId}/holds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["hold"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/verify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["verifyEmail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/verify-email/resend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["resendVerification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["resetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["forgotPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/venues/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tickets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["mine_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tickets/{id}/qr.svg": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["qr"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/organizer/venues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["venues"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/organizer/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["events"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/organizer/events/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["event"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/organizer/events/{id}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["summary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/organizer/events/{id}/scans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["scans"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/organizer/events/{eventId}/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["depth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["export"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{id}/seats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["seats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{eventId}/queue/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["stream"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{eventId}/holds/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["mine_2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/holds/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["release"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateEventRequest: {
            title: string;
            artist: string;
            description: string;
            /** Format: int64 */
            venueId: number;
            /** Format: date-time */
            startsAt: string;
            /** Format: date-time */
            doorsAt: string;
            /** Format: date-time */
            dropOpensAt: string;
            /** Format: date-time */
            onSaleAt: string;
            poster: components["schemas"]["PosterRequest"];
            prices: components["schemas"]["PriceRequest"][];
            waitingRoom: boolean;
        };
        PosterRequest: {
            /** @enum {string} */
            style: "ORBIT" | "SUN" | "CURTAIN" | "AURORA" | "PITCH" | "VINYL";
            inkOne: string;
            inkTwo: string;
            paperColor: string;
        };
        PriceRequest: {
            /** Format: int64 */
            sectionId: number;
            /** Format: int32 */
            priceCents: number;
        };
        EventRef: {
            /** Format: int64 */
            id: number;
            /** @enum {string} */
            status: "DRAFT" | "PUBLISHED" | "CANCELLED";
        };
        LoadGuest: {
            /** Format: int64 */
            id: number;
            token: string;
        };
        CreateVenueRequest: {
            name: string;
            city: string;
            sections: components["schemas"]["SectionRequest"][];
        };
        SectionRequest: {
            name: string;
            /** Format: int32 */
            rows: number;
            /** Format: int32 */
            seatsPerRow: number;
        };
        SectionView: {
            /** Format: int64 */
            id: number;
            name: string;
            /** Format: int32 */
            seats: number;
        };
        VenueView: {
            /** Format: int64 */
            id: number;
            name: string;
            city: string;
            /** Format: int32 */
            totalSeats: number;
            sections: components["schemas"]["SectionView"][];
        };
        ScanRequest: {
            code: string;
            /** Format: int64 */
            eventId: number;
        };
        ScanResult: {
            /** @enum {string} */
            outcome: "VALID" | "ALREADY_USED" | "WRONG_EVENT" | "UNKNOWN";
            seat?: string | null;
            /** Format: date-time */
            usedAt?: string | null;
        };
        PayRequest: {
            /** Format: int64 */
            holdId: number;
            paymentToken: string;
        };
        OrderSeat: {
            /** Format: int64 */
            seatId: number;
            section: string;
            row: string;
            /** Format: int32 */
            number: number;
            /** Format: int64 */
            faceCents: number;
            /** Format: int64 */
            feeCents: number;
        };
        OrderView: {
            /** Format: int64 */
            id: number;
            reference: string;
            /** Format: int64 */
            eventId: number;
            /** @enum {string} */
            status: "PENDING_PAYMENT" | "PAID" | "FAILED" | "REFUNDING" | "REFUNDED";
            /** Format: int64 */
            subtotalCents: number;
            /** Format: int64 */
            feeCents: number;
            /** Format: int64 */
            totalCents: number;
            currency: string;
            failureReason?: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            paidAt?: string | null;
            seats: components["schemas"]["OrderSeat"][];
            tickets: components["schemas"]["TicketView"][];
        };
        TicketView: {
            /** Format: int64 */
            id: number;
            code: string;
            section: string;
            row: string;
            /** Format: int32 */
            number: number;
            /** @enum {string} */
            status: "ISSUED" | "USED" | "VOID";
        };
        CloseRequest: {
            password: string;
        };
        QueueView: {
            /** @enum {string} */
            state: "NOT_IN_QUEUE" | "WAITING" | "ADMITTED";
            /** Format: int64 */
            position?: number | null;
            /** Format: int64 */
            aheadOfYou: number;
            /** Format: int64 */
            queueLength: number;
            /** Format: int64 */
            estimatedWaitSeconds: number;
            admissionToken?: string | null;
            /** Format: date-time */
            admittedUntil?: string | null;
            /** @enum {string} */
            saleState: "NOT_YET" | "QUEUE_OPEN" | "ON_SALE" | "ENDED";
            /** Format: date-time */
            serverTime: string;
        };
        HoldRequest: {
            seatIds: number[];
        };
        HoldSeatView: {
            /** Format: int64 */
            seatId: number;
            section: string;
            row: string;
            /** Format: int32 */
            number: number;
            /** Format: int64 */
            faceCents: number;
        };
        HoldView: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            eventId: number;
            /** Format: date-time */
            expiresAt: string;
            /** Format: date-time */
            serverTime: string;
            seats: components["schemas"]["HoldSeatView"][];
            /** Format: int64 */
            subtotalCents: number;
            /** Format: int64 */
            feeCents: number;
            /** Format: int64 */
            totalCents: number;
        };
        LinkRequest: {
            token: string;
        };
        ResetPasswordRequest: {
            token: string;
            password: string;
        };
        RegisterRequest: {
            /** Format: email */
            email: string;
            password: string;
            displayName: string;
            turnstileToken?: string | null;
        };
        UserResponse: {
            /** Format: int64 */
            id: number;
            email: string;
            displayName: string;
            role: string;
            emailVerified: boolean;
        };
        TokenResponse: {
            accessToken: string;
            tokenType: string;
            /** Format: int64 */
            expiresIn: number;
        };
        LoginRequest: {
            email: string;
            password: string;
        };
        ForgotPasswordRequest: {
            /** Format: email */
            email: string;
        };
        PaymentStats: {
            /** Format: int32 */
            charges: number;
            /** Format: int64 */
            chargedCents: number;
            /** Format: int32 */
            refunds: number;
            chargedKeys: string[];
        };
        MyTicket: {
            /** Format: int64 */
            id: number;
            code: string;
            orderReference: string;
            /** Format: int64 */
            eventId: number;
            section: string;
            row: string;
            /** Format: int32 */
            number: number;
            /** @enum {string} */
            status: "ISSUED" | "USED" | "VOID";
        };
        EventRow: {
            /** Format: int64 */
            id: number;
            title: string;
            /** @enum {string} */
            status: "DRAFT" | "PUBLISHED" | "CANCELLED";
            /** Format: date-time */
            startsAt: string;
            venueName: string;
            city: string;
            /** Format: int32 */
            capacity: number;
            /** Format: int32 */
            sold: number;
            /** Format: int64 */
            grossCents: number;
        };
        PageViewEventRow: {
            items: components["schemas"]["EventRow"][];
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            size: number;
            /** Format: int64 */
            totalItems: number;
            /** Format: int32 */
            totalPages: number;
        };
        OrganizerEvent: {
            /** Format: int64 */
            id: number;
            /** @enum {string} */
            status: "DRAFT" | "PUBLISHED" | "CANCELLED";
            title: string;
            artist: string;
            description: string;
            /** Format: int64 */
            venueId: number;
            /** Format: date-time */
            startsAt: string;
            /** Format: date-time */
            doorsAt: string;
            /** Format: date-time */
            dropOpensAt: string;
            /** Format: date-time */
            onSaleAt: string;
            poster: components["schemas"]["PosterView"];
            prices: components["schemas"]["PriceView"][];
            waitingRoom: boolean;
        };
        PosterView: {
            /** @enum {string} */
            style: "ORBIT" | "SUN" | "CURTAIN" | "AURORA" | "PITCH" | "VINYL";
            inkOne: string;
            inkTwo: string;
            paperColor: string;
        };
        PriceView: {
            /** Format: int64 */
            sectionId: number;
            /** Format: int32 */
            priceCents: number;
        };
        Door: {
            /** Format: int64 */
            issued: number;
            /** Format: int64 */
            checkedIn: number;
        };
        Revenue: {
            /** Format: int64 */
            paidOrders: number;
            /** Format: int64 */
            subtotalCents: number;
            /** Format: int64 */
            feeCents: number;
            /** Format: int64 */
            totalCents: number;
        };
        SalesSummary: {
            /** Format: int64 */
            eventId: number;
            title: string;
            /** @enum {string} */
            status: "DRAFT" | "PUBLISHED" | "CANCELLED";
            tiers: components["schemas"]["TierRow"][];
            revenue: components["schemas"]["Revenue"];
            ordersByStatus: {
                [key: string]: number;
            };
            door: components["schemas"]["Door"];
        };
        TierRow: {
            /** Format: int64 */
            sectionId: number;
            name: string;
            /** Format: int32 */
            priceCents?: number | null;
            /** Format: int32 */
            total: number;
            /** Format: int32 */
            sold: number;
            /** Format: int32 */
            held: number;
            /** Format: int32 */
            available: number;
        };
        ScanRow: {
            code: string;
            outcome: string;
            seat?: string | null;
            /** Format: date-time */
            at: string;
        };
        Depth: {
            /** Format: int64 */
            waiting: number;
            /** Format: int64 */
            inside: number;
        };
        Account: {
            /** Format: int64 */
            id: number;
            email: string;
            displayName: string;
            role: string;
            emailVerified: boolean;
            /** Format: date-time */
            createdAt: string;
        };
        Export: {
            /** Format: date-time */
            exportedAt: string;
            account: components["schemas"]["Account"];
            orders: components["schemas"]["ExportedOrder"][];
            emails: components["schemas"]["ExportedEmail"][];
        };
        ExportedEmail: {
            subject: string;
            kind: string;
            /** Format: date-time */
            sentAt: string;
        };
        ExportedOrder: {
            eventTitle: string;
            order: components["schemas"]["OrderView"];
        };
        EventSummary: {
            /** Format: int64 */
            id: number;
            title: string;
            artist: string;
            /** Format: date-time */
            startsAt: string;
            venueName: string;
            city: string;
            /** Format: date-time */
            dropOpensAt: string;
            /** Format: date-time */
            onSaleAt: string;
            /** @enum {string} */
            saleState: "UPCOMING" | "QUEUE_OPEN" | "ON_SALE" | "ENDED";
            /** Format: int64 */
            fromAllInCents: number;
            poster: components["schemas"]["PosterView"];
        };
        PageViewEventSummary: {
            items: components["schemas"]["EventSummary"][];
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            size: number;
            /** Format: int64 */
            totalItems: number;
            /** Format: int32 */
            totalPages: number;
        };
        EventDetail: {
            /** Format: int64 */
            id: number;
            title: string;
            artist: string;
            description: string;
            /** Format: date-time */
            startsAt: string;
            /** Format: date-time */
            doorsAt: string;
            /** Format: date-time */
            dropOpensAt: string;
            /** Format: date-time */
            onSaleAt: string;
            /** @enum {string} */
            saleState: "UPCOMING" | "QUEUE_OPEN" | "ON_SALE" | "ENDED";
            /** Format: date-time */
            serverTime: string;
            venueName: string;
            city: string;
            poster: components["schemas"]["PosterView"];
            tiers: components["schemas"]["TierView"][];
            /** Format: int32 */
            totalSeats: number;
            /** Format: int32 */
            availableSeats: number;
            waitingRoom: boolean;
            cancelled: boolean;
        };
        TierView: {
            /** Format: int64 */
            sectionId: number;
            name: string;
            /** Format: int64 */
            faceCents: number;
            /** Format: int64 */
            feeCents: number;
            /** Format: int64 */
            allInCents: number;
            /** Format: int32 */
            totalSeats: number;
            /** Format: int32 */
            availableSeats: number;
        };
        RowMap: {
            label: string;
            seats: components["schemas"]["SeatCell"][];
        };
        SeatCell: {
            /** Format: int64 */
            id: number;
            /** Format: int32 */
            number: number;
            status: string;
        };
        SeatMap: {
            sections: components["schemas"]["SectionMap"][];
        };
        SectionMap: {
            /** Format: int64 */
            id: number;
            name: string;
            rows: components["schemas"]["RowMap"][];
        };
        SseEmitter: {
            /** Format: int64 */
            timeout: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    detail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EventDetail"];
                };
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEventRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EventRef"];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateVenueRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["VenueView"];
                };
            };
        };
    };
    scan: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScanRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ScanResult"];
                };
            };
        };
    };
    mine: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OrderView"][];
                };
            };
        };
    };
    pay: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PayRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OrderView"];
                };
            };
        };
    };
    close: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CloseRequest"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list: {
        parameters: {
            query?: {
                city?: string;
                q?: string;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageViewEventSummary"];
                };
            };
        };
    };
    create_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEventRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EventRef"];
                };
            };
        };
    };
    publish: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EventRef"];
                };
            };
        };
    };
    cancel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EventRef"];
                };
            };
        };
    };
    status: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["QueueView"];
                };
            };
        };
    };
    join: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["QueueView"];
                };
            };
        };
    };
    leave: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    hold: {
        parameters: {
            query?: never;
            header?: {
                "X-Admission-Token"?: string;
            };
            path: {
                eventId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HoldRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HoldView"];
                };
            };
        };
    };
    verifyEmail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LinkRequest"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    resendVerification: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    resetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordRequest"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TokenResponse"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TokenResponse"];
                };
            };
        };
    };
    forgotPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotPasswordRequest"];
            };
        };
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["VenueView"];
                };
            };
        };
    };
    mine_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MyTicket"][];
                };
            };
        };
    };
    qr: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/svg+xml": string;
                };
            };
        };
    };
    venues: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["VenueView"][];
                };
            };
        };
    };
    events: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageViewEventRow"];
                };
            };
        };
    };
    event: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OrganizerEvent"];
                };
            };
        };
    };
    summary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SalesSummary"];
                };
            };
        };
    };
    scans: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ScanRow"][];
                };
            };
        };
    };
    depth: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Depth"];
                };
            };
        };
    };
    get_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OrderView"];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    export: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Export"];
                };
            };
        };
    };
    seats: {
        parameters: {
            query?: {
                section?: number;
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SeatMap"];
                };
            };
        };
    };
    stream: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["SseEmitter"];
                };
            };
        };
    };
    mine_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HoldView"];
                };
            };
        };
    };
    release: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
