import type { components } from './schema'

type Schemas = components['schemas']

export type EventSummary = Schemas['EventSummary']
export type EventDetail = Schemas['EventDetail']
export type TierView = Schemas['TierView']
export type PosterView = Schemas['PosterView']
export type SeatMap = Schemas['SeatMap']
export type HoldView = Schemas['HoldView']
export type QueueView = Schemas['QueueView']
export type OrderView = Schemas['OrderView']
export type MyTicket = Schemas['MyTicket']
export type EventRow = Schemas['EventRow']
export type SalesSummary = Schemas['SalesSummary']
export type TierRow = Schemas['TierRow']
export type ScanRow = Schemas['ScanRow']
export type ScanResult = Schemas['ScanResult']
export type QueueDepth = Schemas['Depth']
export type VenueView = Schemas['VenueView']
export type CreateVenueRequest = Schemas['CreateVenueRequest']
export type CreateEventRequest = Schemas['CreateEventRequest']
export type EventStatus = EventRow['status']
