// Regenerates src/api/schema.d.ts from the running backend's OpenAPI document.
//   npm run api:types              (backend on http://localhost:8080, or set BACKEND_URL)
// Load-test hooks (/dev/*) only exist under a profile and are not part of the app's contract, so they are dropped.
import { mkdirSync, writeFileSync } from 'node:fs'
import openapiTS, { astToString } from 'openapi-typescript'

const base = process.env.BACKEND_URL ?? 'http://localhost:8080'
const spec = await (await fetch(`${base}/v3/api-docs`)).json()
for (const path of Object.keys(spec.paths)) {
  if (path.startsWith('/dev/')) delete spec.paths[path]
}

const banner = '/* Generated by `npm run api:types` from the backend\'s OpenAPI document. Do not edit. */\n'
const ast = await openapiTS(spec)
mkdirSync(new URL('../src/api/', import.meta.url), { recursive: true })
writeFileSync(new URL('../src/api/schema.d.ts', import.meta.url), banner + astToString(ast))
console.log(`Wrote src/api/schema.d.ts from ${base} (${Object.keys(spec.paths).length} paths)`)
